/* ───────────────────────────────────────────────────────────────────────────
   LEGAL PAGES

   Copied verbatim from the main Zan app (zan_webdevelopment/src/data/legal.ts),
   which migrated it verbatim from the previous site. This text is legally operative —
   it covers DPDP Act (2023) obligations, the US entity's EIN, refund terms and
   cookie disclosure — so it is carried across word for word rather than
   rewritten. Edits belong with whoever drafted it, not in a design pass.

   Structure is flattened to tagged blocks so one renderer can lay out all five
   pages consistently.
   ─────────────────────────────────────────────────────────────────────────── */

export interface LegalBlock {
  tag: "h2" | "h3" | "h4" | "p" | "li";
  text: string;
}

export interface LegalDocument {
  title: string;
  /** Effective date as published on the previous site. */
  effective: string;
  blocks: LegalBlock[];
}

export const legalDocuments: Record<string, LegalDocument> = {
  "privacy-policy": {
    title: "Privacy Policy",
    effective: "January 27, 2026",
    blocks: [
      { tag: "p", text: "Zan Services (\"we,\" \"us,\" or \"our\"), headquartered in Kolkata, West Bengal, India, with a US presence through Zan Services LLC (EIN: 35-2955914) at 2108 N St Ste N, Sacramento, CA 95816, USA, is committed to protecting your privacy. This Privacy Policy describes how we collect, use, process, store, share, and protect your personal data when you visit our website zanservices.com, contact us, request quotes, engage our services (web development, mobile apps, blockchain/Web3, AI solutions, digital marketing), or interact with us in any way." },
      { tag: "p", text: "We act as a Data Fiduciary under India's Digital Personal Data Protection Act, 2023 (DPDP Act) for digital personal data we process. By using our website or services, you consent to the practices described here. If you do not agree, please do not use our website or provide us with any personal data." },
      { tag: "h2", text: "1. Personal Data We Collect" },
      { tag: "p", text: "We collect only the data necessary for the specified purposes (data minimization principle)." },
      { tag: "h3", text: "Personal Data You Provide Directly" },
      { tag: "li", text: "Contact details: name, email address, phone number, postal address." },
      { tag: "li", text: "Professional/project details: company name, job title, industry, project requirements, specifications, or files you share for web/mobile/blockchain/AI development quotes or projects." },
      { tag: "li", text: "Account data (if applicable): login credentials for client portals." },
      { tag: "li", text: "Payment information: billing details (processed securely via third-party gateways; we do not store full card details)." },
      { tag: "li", text: "Other: feedback, survey responses, or communications." },
      { tag: "h3", text: "Automatically Collected Data" },
      { tag: "li", text: "Technical/usage data: IP address, browser type/version, device information, operating system, pages visited, time/date of access, referral sources, and interactions." },
      { tag: "li", text: "Cookies & tracking: See our Cookie Policy section below." },
      { tag: "p", text: "We do not knowingly collect sensitive personal data (e.g., health, financial beyond payment processing, biometric) unless explicitly required for a service you request and with your consent." },
      { tag: "h2", text: "2. How We Collect Personal Data" },
      { tag: "li", text: "Directly from you: contact forms, quote requests, emails, calls, project discussions." },
      { tag: "li", text: "Automatically: cookies, server logs, analytics tools (e.g., Google Analytics)." },
      { tag: "li", text: "From third parties: rarely, e.g., analytics providers or business referrals (with safeguards)." },
      { tag: "h2", text: "3. Purposes of Processing & Lawful Basis" },
      { tag: "p", text: "We process personal data only for specified, legitimate purposes and retain it no longer than necessary:" },
      { tag: "p", text: "Under the DPDP Act, processing is based on your consent or legitimate uses (e.g., contract performance, legal compliance)." },
      { tag: "h2", text: "4. Sharing & Disclosure of Personal Data" },
      { tag: "p", text: "We do not sell your personal data. Sharing is limited to:" },
      { tag: "h2", text: "5. International Data Transfers" },
      { tag: "p", text: "As an India-based company, we may transfer data to service providers outside India (e.g., cloud servers in the US/EU). We ensure appropriate safeguards (e.g., contractual clauses) to maintain protection levels consistent with the DPDP Act and this policy." },
      { tag: "h2", text: "6. Data Security" },
      { tag: "p", text: "We implement reasonable technical, organizational, and physical safeguards (encryption, access controls, firewalls, regular audits) to protect against unauthorized access, loss, or misuse. However, no system is 100% secure. In case of a breach affecting your data, we will notify you and authorities as required by law." },
      { tag: "h2", text: "7. Data Retention" },
      { tag: "p", text: "We retain personal data only as long as necessary for the purpose, legal obligations, or dispute resolution — typically project duration + support period (e.g., 3 months post-launch) or longer if required by law. After that, we securely delete or anonymize it." },
      { tag: "h2", text: "8. Your Rights as Data Principal" },
      { tag: "p", text: "Under the DPDP Act and other applicable laws, you have the right to:" },
      { tag: "p", text: "To exercise rights, contact us (details below). We respond within statutory timelines (usually 30 days or as prescribed)." },
      { tag: "h2", text: "9. Cookie Policy" },
      { tag: "p", text: "We use cookies and similar technologies for functionality, analytics, and performance. Essential cookies are necessary for site operation; others require consent. You can manage your cookie preferences via your browser settings. We use the following tracking technologies:" },
      { tag: "li", text: "Google Analytics / Google Ads (gtag.js): for website analytics and advertising conversion tracking." },
      { tag: "li", text: "Meta Pixel (Facebook): for advertising performance and audience insights." },
      { tag: "p", text: "These tools may collect data such as pages visited, time on site, and interactions. You can opt out via browser settings or third-party opt-out tools." },
      { tag: "h2", text: "10. Children's Privacy" },
      { tag: "p", text: "Our services are not directed at children under 18. We do not knowingly process data of children without verifiable parental/guardian consent as required by law." },
      { tag: "h2", text: "11. Third-Party Links & Services" },
      { tag: "p", text: "Our site may link to third-party websites/tools. We are not responsible for their privacy practices — review them separately." },
      { tag: "h2", text: "12. Changes to This Privacy Policy" },
      { tag: "p", text: "We may update this policy to reflect changes in practices, services, or law. Changes are posted here with a new effective date. Material changes will be notified via website notice or email (where appropriate). Continued use after changes means acceptance." },
      { tag: "h2", text: "13. Contact & Grievance Redressal" },
      { tag: "p", text: "For privacy queries, rights requests, or complaints, contact us with \"Privacy Query\" in the subject:" },
      { tag: "h3", text: "Grievance Officer / Contact Person" },
      { tag: "p", text: "Zan Services" },
      { tag: "p", text: "Governing Law: This policy is governed by the laws of India, including the Digital Personal Data Protection Act, 2023." },
    ],
  },
  "terms-of-service": {
    title: "Terms & Conditions",
    effective: "January 27, 2026",
    blocks: [
      { tag: "p", text: "These Terms and Conditions (\"Terms,\" \"Agreement\") govern your access to and use of the website zanservices.com (\"Website\") and the services provided by Zan Services (\"we,\" \"us,\" \"our,\" or \"Zan Services\"), a company headquartered in Kolkata, West Bengal, India, with a US presence through Zan Services LLC (EIN: 35-2955914) at 2108 N St Ste N, Sacramento, CA 95816, USA. Our services include, but are not limited to, web development, mobile application development, blockchain and Web3 solutions, AI and machine learning services, digital marketing, IT consulting, software development, and related digital solutions (\"Services\")." },
      { tag: "p", text: "By accessing the Website, requesting a quote, entering into a project agreement, or using our Services, you (\"you,\" \"Client,\" or \"user\") agree to be bound by these Terms. If you are entering into these Terms on behalf of a company or other legal entity, you represent that you have the authority to bind that entity." },
      { tag: "p", text: "If you do not agree with these Terms, do not access the Website or use our Services." },
      { tag: "h2", text: "1. Services" },
      { tag: "p", text: "1.1 Description. We provide custom digital solutions as described on our Website or in project proposals/quotes. Services are performed based on the scope agreed in writing (e.g., via proposal, statement of work/SOW, or contract)." },
      { tag: "p", text: "1.2 Scope of Work. The specific deliverables, timelines, milestones, and requirements will be detailed in a separate project agreement, SOW, or quote accepted by both parties. Any changes must be agreed in writing and may result in adjustments to fees, timelines, or scope." },
      { tag: "p", text: "1.3 Client Responsibilities. You agree to:" },
      { tag: "li", text: "Provide accurate, complete, and timely information, content, materials, approvals, and feedback." },
      { tag: "li", text: "Grant us necessary access, licenses, and permissions to perform the Services." },
      { tag: "li", text: "Comply with all applicable laws, including data protection laws." },
      { tag: "p", text: "We are not responsible for delays or issues caused by your failure to meet these obligations." },
      { tag: "h2", text: "2. Payment Terms" },
      { tag: "p", text: "2.1 Fees. Fees are as specified in the quote, proposal, or SOW. All prices are in INR (or as agreed) and exclusive of taxes (GST, etc.), which you are responsible for." },
      { tag: "p", text: "2.2 Payment Schedule. Unless otherwise agreed:" },
      { tag: "li", text: "30-50% advance/deposit upon acceptance." },
      { tag: "li", text: "Milestone-based payments (e.g., 30% on design approval, 30% on development completion, balance on delivery)." },
      { tag: "li", text: "Final payment upon project completion and sign-off." },
      { tag: "p", text: "2.3 Invoicing and Payment. Invoices are due within 7-15 days (as specified). Late payments attract interest at 1.5% per month or the maximum allowed by law. We may suspend Services for non-payment." },
      { tag: "p", text: "2.4 Expenses. You reimburse reasonable out-of-pocket expenses (e.g., third-party tools/licenses) pre-approved in writing." },
      { tag: "p", text: "2.5 Taxes. You are responsible for all applicable taxes, duties, and levies." },
      { tag: "h2", text: "3. Intellectual Property" },
      { tag: "p", text: "3.1 Pre-Existing IP. Each party retains ownership of its pre-existing intellectual property." },
      { tag: "p", text: "3.2 Client-Owned Deliverables. Upon full payment, we assign to you all rights, title, and interest in final deliverables specifically created for you under the project (e.g., custom code, designs, content), except for:" },
      { tag: "li", text: "Pre-existing materials, templates, frameworks, or third-party components we use (licensed to you on a non-exclusive, perpetual basis for the project)." },
      { tag: "li", text: "General know-how, tools, methodologies, or reusable code/components." },
      { tag: "p", text: "3.3 Our Rights. We retain rights to:" },
      { tag: "li", text: "Use anonymized project examples in our portfolio/marketing (unless you object in writing)." },
      { tag: "li", text: "Reuse non-proprietary code, templates, or techniques developed during the project." },
      { tag: "p", text: "3.4 Third-Party Materials. Any third-party software, libraries, APIs, or assets are subject to their licenses; we provide them \"as is.\"" },
      { tag: "p", text: "3.5 License Grant. You grant us a limited, non-exclusive license to use your materials solely to provide the Services." },
      { tag: "h2", text: "4. Confidentiality" },
      { tag: "p", text: "Both parties agree to keep confidential any non-public information disclosed during the engagement and use it only for the purpose of the Services. This obligation survives termination for 3 years (or longer for trade secrets)." },
      { tag: "h2", text: "5. Warranties and Disclaimers" },
      { tag: "p", text: "5.1 Our Warranties. We warrant that Services will be performed in a professional, workmanlike manner consistent with industry standards." },
      { tag: "p", text: "5.2 Client Warranties. You warrant that all materials provided do not infringe third-party rights and comply with laws." },
      { tag: "p", text: "5.3 No Other Warranties. EXCEPT AS EXPRESSLY STATED, SERVICES AND DELIVERABLES ARE PROVIDED \"AS IS.\" WE DISCLAIM ALL OTHER WARRANTIES, EXPRESS OR IMPLIED, INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, OR ERROR-FREE OPERATION." },
      { tag: "p", text: "We do not guarantee specific business results (e.g., traffic, rankings, revenue from digital marketing)." },
      { tag: "h2", text: "6. Limitation of Liability" },
      { tag: "p", text: "TO THE MAXIMUM EXTENT PERMITTED BY LAW:" },
      { tag: "li", text: "WE SHALL NOT BE LIABLE FOR INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL, PUNITIVE, OR EXEMPLARY DAMAGES (INCLUDING LOSS OF PROFITS, DATA, GOODWILL), EVEN IF ADVISED OF THE POSSIBILITY." },
      { tag: "li", text: "OUR TOTAL LIABILITY ARISING FROM OR RELATED TO THE SERVICES SHALL NOT EXCEED THE FEES PAID BY YOU UNDER THE RELEVANT PROJECT IN THE 12 MONTHS PRECEDING THE CLAIM." },
      { tag: "li", text: "WE ARE NOT LIABLE FOR DELAYS, FAILURES, OR ISSUES CAUSED BY THIRD PARTIES, YOUR ACTIONS, FORCE MAJEURE, OR INTERNET/TECHNICAL ISSUES." },
      { tag: "h2", text: "7. Indemnification" },
      { tag: "p", text: "You agree to indemnify, defend, and hold us harmless from claims, losses, liabilities, damages, costs (including reasonable attorneys' fees) arising from:" },
      { tag: "p", text: "We will indemnify you for claims that our Services infringe third-party IP (subject to prompt notice and cooperation; we may modify or replace to avoid infringement)." },
      { tag: "h2", text: "8. Termination" },
      { tag: "p", text: "8.1 By Either Party. For material breach (with 15-30 days' written notice to cure, except non-payment which is 7 days)." },
      { tag: "p", text: "8.2 Effect of Termination. Upon termination:" },
      { tag: "p", text: "8.3 Suspension. We may suspend Services for non-payment or breach." },
      { tag: "h2", text: "9. Force Majeure" },
      { tag: "p", text: "Neither party is liable for delays or failures due to events beyond reasonable control (e.g., natural disasters, war, government actions, pandemics, internet outages)." },
      { tag: "h2", text: "10. Governing Law and Dispute Resolution" },
      { tag: "p", text: "10.1 Governing Law. These Terms are governed by the laws of India, without regard to conflict of laws principles." },
      { tag: "p", text: "10.2 Jurisdiction. Exclusive jurisdiction lies with courts in Kolkata, West Bengal, India." },
      { tag: "p", text: "10.3 Dispute Resolution. Any disputes first attempted to be resolved amicably within 30 days. Failing that, through arbitration in Kolkata under the Arbitration and Conciliation Act, 1996 (as amended), with one arbitrator appointed mutually." },
      { tag: "h2", text: "11. Miscellaneous" },
      { tag: "p", text: "11.1 Entire Agreement. These Terms (plus any SOW/project agreement) constitute the entire agreement, superseding prior understandings." },
      { tag: "p", text: "11.2 Amendments. Only in writing signed by both parties." },
      { tag: "p", text: "11.3 Severability. Invalid provisions do not affect others." },
      { tag: "p", text: "11.4 Assignment. You may not assign without our consent; we may assign to affiliates or in business transfers." },
      { tag: "p", text: "11.5 Waiver. No waiver unless in writing." },
      { tag: "p", text: "11.6 Notices. In writing via email or registered post to the addresses provided." },
      { tag: "p", text: "11.7 Independent Contractors. No partnership, joint venture, or agency created." },
      { tag: "p", text: "11.8 Compliance with Laws. Both parties comply with applicable laws, including the Digital Personal Data Protection Act, 2023 (DPDP Act) for personal data processing." },
      { tag: "h2", text: "Contact Us" },
      { tag: "p", text: "Zan Services" },
    ],
  },
  "refund-policy": {
    title: "Refund & Cancellation Policy",
    effective: "January 27, 2026",
    blocks: [
      { tag: "p", text: "This Refund and Cancellation Policy (\"Policy\") forms part of our Terms and Conditions and applies to all services provided by Zan Services (\"we,\" \"us,\" or \"our\"), including web development, mobile app development, blockchain & Web3 solutions, AI solutions, digital marketing, SEO, social media management, and related digital services." },
      { tag: "p", text: "We aim to deliver high-quality work and maintain transparent client relationships. However, due to the custom, project-based, and time-intensive nature of our services, refunds and cancellations are limited and governed by this Policy." },
      { tag: "p", text: "By engaging our services, making any payment, or accepting a quote/proposal, you agree to this Policy." },
      { tag: "h2", text: "1. General Principles" },
      { tag: "h2", text: "2. Advance / Deposit Payments" },
      { tag: "li", text: "We typically require an advance/deposit (30-50% of total project fee) upon acceptance of the quote or signing of the Statement of Work (SOW)/project agreement." },
      { tag: "li", text: "This advance/deposit is non-refundable once we commence work (e.g., planning, research, initial designs, or resource allocation)." },
      { tag: "li", text: "If the project is cancelled before any work begins (i.e., no deliverables, designs, code, or time logged), we may, at our sole discretion, refund up to 50-70% of the advance after deducting administrative, consultation, and opportunity costs." },
      { tag: "h2", text: "3. Milestone-Based Payments and Refunds" },
      { tag: "p", text: "Projects are structured with milestones (e.g., planning, design approval, development phases, testing, deployment)." },
      { tag: "li", text: "Refunds are only considered for uncompleted milestones and are proportional to work not yet performed." },
      { tag: "li", text: "Once a milestone is approved/completed and payment received, that portion is non-refundable." },
      { tag: "p", text: "Refund scenarios (subject to our discretion):" },
      { tag: "p", text: "Planning/Requirement Gathering Phase (before designs or code): Up to 70-80% refund of payments made for this phase." },
      { tag: "p", text: "Design/Prototype Phase (after approval): No refund for approved designs; partial refund (40-60%) if no approval given and minimal revisions done." },
      { tag: "p", text: "Development/Implementation Phase: No refund for completed code, features, or modules delivered and accepted." },
      { tag: "p", text: "Testing/Deployment Phase: No refund once live or handed over." },
      { tag: "p", text: "Refunds will deduct:" },
      { tag: "h2", text: "4. No-Refund Situations" },
      { tag: "p", text: "No refunds will be issued in the following cases:" },
      { tag: "h2", text: "5. Cancellation Procedure" },
      { tag: "li", text: "Cancellation must be requested in writing via email to support@zanservices.com with clear subject: \"Project Cancellation Request – [Project Name]\"." },
      { tag: "li", text: "Provide reasons and current status." },
      { tag: "li", text: "We will acknowledge within 2 business days and provide a final invoice/settlement statement showing work completed, any refund due, and outstanding balance." },
      { tag: "li", text: "You must settle any outstanding payments before cancellation takes effect." },
      { tag: "li", text: "Upon mutual agreement, we will cease work and deliver any partially completed materials (subject to full payment for work done)." },
      { tag: "h2", text: "6. Limited Warranty and Remedies" },
      { tag: "li", text: "We provide a limited post-delivery support period (typically 7-30 days as per SOW) for bug fixes at no extra cost if defects are due to our fault." },
      { tag: "li", text: "If major issues arise within this period that we cannot resolve, you may request cancellation with a proportional refund for undelivered portions only." },
      { tag: "li", text: "This is your sole remedy; no further refunds or damages." },
      { tag: "h2", text: "7. Force Majeure and Exceptional Cases" },
      { tag: "p", text: "In rare cases (e.g., prolonged illness, unforeseen business closure), we may offer goodwill refunds or alternative resolutions at our discretion." },
      { tag: "h2", text: "8. Governing Law and Disputes" },
      { tag: "p", text: "This Policy is governed by the laws of India and subject to the dispute resolution clause in our Terms and Conditions (arbitration in Kolkata)." },
      { tag: "h2", text: "Contact Us" },
      { tag: "p", text: "For refund/cancellation queries:" },
      { tag: "p", text: "Zan Services" },
    ],
  },
  "cookie-policy": {
    title: "Cookie Policy",
    effective: "January 27, 2026",
    blocks: [
      { tag: "p", text: "Zan Services (\"we,\" \"us,\" or \"our\"), headquartered in Kolkata, West Bengal, India, with a US presence through Zan Services LLC (EIN: 35-2955914) at 2108 N St Ste N, Sacramento, CA 95816, USA, is committed to being transparent about how we use cookies and similar technologies on our website zanservices.com (\"Website\")." },
      { tag: "p", text: "This Cookie Policy explains what cookies are, the types we use (or may use), why we use them, and how you can manage or disable them. It forms part of our Privacy Policy and should be read together with it." },
      { tag: "p", text: "By continuing to browse or use our Website, you consent to our use of cookies as described below (except for strictly necessary cookies, which do not require consent). If you do not agree, please disable cookies via your browser settings and refrain from using the Website." },
      { tag: "h2", text: "1. What Are Cookies?" },
      { tag: "p", text: "Cookies are small text files placed on your device (computer, mobile, tablet) by websites you visit. They help the site remember your actions and preferences (e.g., login, language, font size) over time, so you don't have to re-enter them when you return or navigate pages." },
      { tag: "p", text: "Cookies can be:" },
      { tag: "li", text: "First-party cookies: Set by us (zanservices.com)." },
      { tag: "li", text: "Third-party cookies: Set by external providers (e.g., analytics or advertising services)." },
      { tag: "li", text: "Session cookies: Temporary; deleted when you close your browser." },
      { tag: "li", text: "Persistent cookies: Remain on your device for a set period or until deleted." },
      { tag: "p", text: "We may also use similar technologies like web beacons, pixels, local storage, or tracking scripts." },
      { tag: "h2", text: "2. Cookies We Use (or May Use)" },
      { tag: "p", text: "We categorize cookies as follows:" },
      { tag: "h3", text: "2.1 Strictly Necessary / Essential Cookies" },
      { tag: "li", text: "Purpose: Enable core Website functionality (e.g., navigation, secure areas, load balancing, session management)." },
      { tag: "li", text: "Legal basis: Legitimate interests / necessary for providing the service (no consent required under most laws, including DPDP Act for essential processing)." },
      { tag: "li", text: "Examples: Session management, security tokens, basic form handling." },
      { tag: "li", text: "Duration: Mostly session-based or short-term (days)." },
      { tag: "li", text: "Provider: First-party (us)." },
      { tag: "p", text: "These cookies are always active and cannot be disabled without breaking site functionality." },
      { tag: "h3", text: "2.2 Analytics / Performance Cookies" },
      { tag: "li", text: "Purpose: Collect anonymous data on how visitors use the Website (pages viewed, time spent, bounce rates, traffic sources) to improve performance and user experience." },
      { tag: "li", text: "Legal basis: Your consent (opt-in required under DPDP Act for non-essential processing of digital personal data)." },
      { tag: "li", text: "Examples: Visitor counts, navigation patterns, device/browser info." },
      { tag: "li", text: "Duration: Persistent (up to 2 years or as set by provider)." },
      { tag: "li", text: "Provider: Google Analytics (third-party) — uses cookies like _ga, _gid, _gat to distinguish users/sessions. Data may be transferred to and processed in the US or other countries by Google." },
      { tag: "h3", text: "2.3 Functional / Preference Cookies" },
      { tag: "li", text: "Purpose: Remember your preferences (e.g., language, dark mode if available, form inputs) to provide a personalized experience." },
      { tag: "li", text: "Legal basis: Consent." },
      { tag: "li", text: "Examples: Preference storage, chat widget settings (if added)." },
      { tag: "li", text: "Provider: First-party or third-party (e.g., live chat tools)." },
      { tag: "h3", text: "2.4 Marketing / Advertising Cookies" },
      { tag: "li", text: "Purpose: Track your visits to show relevant ads, measure ad effectiveness, or enable remarketing." },
      { tag: "li", text: "Legal basis: Consent (if implemented)." },
      { tag: "li", text: "Examples: Google Ads (gtag.js), Meta Pixel (Facebook) for conversion tracking and audience insights." },
      { tag: "li", text: "Duration: Persistent." },
      { tag: "li", text: "Provider: Third-party (Google, Meta)." },
      { tag: "h2", text: "3. How We Obtain Consent" },
      { tag: "h2", text: "4. How to Manage or Disable Cookies" },
      { tag: "p", text: "You control cookies through:" },
      { tag: "p", text: "Browser Settings" },
      { tag: "p", text: "Most browsers let you block all cookies, block third-party cookies, delete cookies on exit, or see cookie details:" },
      { tag: "li", text: "Chrome: Settings > Privacy and security > Cookies and other site data" },
      { tag: "li", text: "Firefox: Preferences > Privacy & Security > Cookies and Site Data" },
      { tag: "li", text: "Safari: Preferences > Privacy > Manage Website Data" },
      { tag: "p", text: "Opt-Out Tools" },
      { tag: "li", text: "Google Analytics Opt-Out: Install the Google Analytics Opt-Out Browser Add-on from tools.google.com" },
      { tag: "li", text: "Your Online Choices: Visit youronlinechoices.com for third-party ad opt-out" },
      { tag: "p", text: "Disabling non-essential cookies may not affect site functionality but could limit analytics insights for us and personalized features for you." },
      { tag: "h2", text: "5. Updates to This Cookie Policy" },
      { tag: "p", text: "We may update this policy to reflect changes in technology, services, or law. Check back periodically; material changes will be notified via Website notice or email (if we have your contact). Continued use after changes means acceptance." },
      { tag: "h2", text: "6. Contact Us" },
      { tag: "p", text: "Questions about cookies?" },
      { tag: "p", text: "Zan Services" },
    ],
  },
  "disclaimer": {
    title: "Disclaimer",
    effective: "January 27, 2026",
    blocks: [
      { tag: "p", text: "Zan Services (\"we,\" \"us,\" \"our,\" or \"Zan Services\"), a digital solutions and IT services company headquartered in Kolkata, West Bengal, India, with a US presence through Zan Services LLC (EIN: 35-2955914) at 2108 N St Ste N, Sacramento, CA 95816, USA, provides development, consulting, and related services, including Blockchain and Web3 solutions such as decentralized applications (DApps), smart contracts, NFT marketplaces, DeFi platforms, token systems, wallet integrations, and custom blockchain development primarily on networks like Ethereum and Polygon." },
      { tag: "p", text: "This Disclaimer applies to all content on our website (zanservices.com), marketing materials, proposals, communications, services, deliverables, and any interactions with us." },
      { tag: "h2", text: "1. No Financial, Investment, Legal, Tax, or Regulatory Advice" },
      { tag: "p", text: "We are not a financial advisor, investment advisor, broker, lawyer, accountant, tax consultant, or regulatory expert. Nothing we provide — whether in proposals, consultations, code, smart contracts, documentation, blog posts, emails, calls, or any other form — constitutes or should be construed as:" },
      { tag: "p", text: "Any information related to blockchain, Web3, cryptocurrencies, DeFi, NFTs, tokens, or related technologies is provided for informational and technical development purposes only. You should never make financial, investment, or legal decisions based on our services, deliverables, or communications without consulting qualified independent professionals (e.g., licensed financial advisors, lawyers, tax experts)." },
      { tag: "h2", text: "2. We Do Not Engage in Crypto Trading, Custody, or Financial Services" },
      { tag: "p", text: "Zan Services does not:" },
      { tag: "p", text: "Our role is strictly technical development and consulting — building tools, applications, and smart contracts as per your instructions." },
      { tag: "h2", text: "3. Inherent Risks of Blockchain, Cryptocurrencies, and Web3" },
      { tag: "p", text: "Blockchain technology, smart contracts, cryptocurrencies, DeFi, NFTs, and Web3 involve significant risks, including but not limited to:" },
      { tag: "p", text: "We are not responsible or liable for any losses, damages, or consequences arising from these risks, even if related to deliverables we provide. You assume full responsibility for conducting your own due diligence, security audits, legal reviews, and risk assessments before deploying, launching, or using any blockchain/Web3 solution." },
      { tag: "h2", text: "4. Third-Party Tools, Networks, and Services" },
      { tag: "p", text: "Our services may integrate or rely on third-party protocols, blockchains (e.g., Ethereum, Polygon), wallets, APIs, libraries, or tools. We do not control, endorse, or guarantee the availability, security, performance, or compliance of these third parties. Any issues, downtime, hacks, or changes with third-party elements are not our responsibility." },
      { tag: "h2", text: "5. No Guarantees on Performance or Outcomes" },
      { tag: "p", text: "We do not guarantee:" },
      { tag: "p", text: "Results depend on many factors outside our control." },
      { tag: "h2", text: "6. Indemnification and Limitation of Liability" },
      { tag: "p", text: "By engaging our services, you agree to indemnify and hold us harmless from any claims, losses, or liabilities arising from your use of deliverables in blockchain/Web3 contexts, including regulatory actions, user losses, or disputes. Our liability remains subject to the limitations in our Terms and Conditions." },
      { tag: "h2", text: "7. Governing Law" },
      { tag: "p", text: "This Disclaimer is governed by the laws of India. Any disputes shall be resolved as per our Terms and Conditions." },
      { tag: "p", text: "By using our website, requesting services, or engaging us for Blockchain/Web3 work, you acknowledge that you have read, understood, and agree to this Disclaimer." },
      { tag: "p", text: "If you do not agree, please do not use our services or provide us with any instructions related to blockchain, crypto, or Web3." },
      { tag: "h2", text: "Contact Us" },
      { tag: "p", text: "For questions about this Disclaimer:" },
      { tag: "p", text: "Zan Services" },
    ],
  }
};
